version: "3.4"

services:

  nginx:
    restart: always
    image: newecopeoplev1/nginx_dev
    ports:
      - "80:80"

  frontend:
    image: newecopeoplev1/frontend_dev

  backend:
    image: newecopeoplev1/backend_dev
    environment:
      - DefaultConnection=Filename=StagingDb.db
      - ASPNETCORE_ENVIRONMENT=Staging
      - AUTHORIZATION_TOKEN=Thisismenttobethesupersecretpassword
      - HOSTNAME=http://localhost
    ports:
      - "5000:5000"

  nginx_template:
    restart: always
    image: newecopeoplev1/nginx_template_dev
    ports:
      - "4000:4000"

  template:
    image: newecopeoplev1/template_dev